name: Backlog Entry
description: Add a new entry to the backlog.
title: "[Backlog]: "
labels: ["backlog"]
type: feature
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this issue!
  - type: checkboxes
    id: checklist
    attributes:
      label: Confirmations
      description: "Please confirm the following"
      options:
        - label: Backlog entry requires creating new sandboxes.
          required: false
        - label: Backlog entry requires creating new exploitation code and / or tutorials.
          required: false
        - label: Backlog entry entry introduces and / or exploits CVEs.
          required: false
  - type: input
    id: cve
    attributes:
      label: CVE List
      description: If this entry involves introducing and / or exploiting CVEs, please list their codes below (comma separated).
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Description?
      description: Provide as much detail as possible.
    validations:
      required: true